swagger: "2.0"
info:
  version: 1.0.0
  title: expressBoilerplate
  description: Express boilerplate
basePath: /api/v1
tags:
  - name: Examples
    description: Simple example endpoints
  - name: Specification
    description: The swagger API specification
  - name: Colombia's weather
    description: Enpoints for Colombia's annual average weather  

consumes:
  - application/json
produces:
  - application/json

definitions:
  ExampleBody:
    type: object
    title: example
    required:
      - name
    properties:
      name:
        type: string
        description: The example name
  WeatherBody:
    type: object
    title: weather
    required:
      - year
      - weather
    properties:
      year:
        type: integer
        description: The year
      weather:
        type: number
        description: The weather correspondig to the year   

paths:
  /examples:
    get:
      tags:
        - Examples
      description: Fetch all examples
      responses:
        200:
          description: Returns all examples
    post:
      tags:
        - Examples
      description: Create a new example
      parameters:
        - name: example
          in: body
          description: number of items to skip
          required: true
          schema: 
            $ref: "#/definitions/ExampleBody"
      responses:
        200:
          description: Returns all examples
  /weathercol:
    get:
      tags:
        - Colombia's weather
      description: Fetch all entries of Colombia's weather
      responses:
        200:
          description: Returns all entries of Colombia's weather
    post:
      tags:
        - Colombia's weather
      description: Create a new entrie of Colombia's weather
      parameters:
        - name: The weather correspondig to the year
          in: body
          description: A year with it's weather
          required: true
          schema: 
            $ref: "#/definitions/WeatherBody"
      responses:
        200:
          description: Returns all entries of Colombia's weather

  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification